package Vista;

import Controlador.CtrlConsultarProducto;
import Controlador.CtrlConsultarUsuario;
import Controlador.CtrlConsultarproveedor;
import Controlador.CtrlEliminarProducto;
import Controlador.CtrlEliminarProveedor;
import Controlador.CtrlEliminarUsuario;
import Controlador.CtrlModificarContraseña;
import Controlador.CtrlModificarProducto;
import Controlador.CtrlModificarProveedor;
import Controlador.CtrlModificarUsuario;
import Controlador.CtrlProducto;
import Controlador.CtrlRegistrarUsuario;
import Controlador.CtrlRegistrarproveedor;
import Modelo.ConsultasProducto;
import Modelo.ConsultasProveedor;
import Modelo.ConsultasUsuario;
import Modelo.Producto;
import Modelo.Proveedor;
import Modelo.Usuario;

/**
 *
 * @author Judith
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuVentas = new javax.swing.JMenu();
        ItemRegistrarventa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenu();
        ItemRegistrarproducto = new javax.swing.JMenuItem();
        Menuproveedores = new javax.swing.JMenu();
        ItemRegistrarproveedor = new javax.swing.JMenuItem();
        MenuCompra = new javax.swing.JMenu();
        ItemRegistrarcompra = new javax.swing.JMenuItem();
        Menureportes = new javax.swing.JMenu();
        ItemGenerarreporte = new javax.swing.JMenuItem();
        Menuusuarios = new javax.swing.JMenu();
        ItemRegistrarusuario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1094, 705));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vb.jpg"))); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MenuVentas.setText("Ventas");

        ItemRegistrarventa.setText("Registrar venta");
        ItemRegistrarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegistrarventaActionPerformed(evt);
            }
        });
        MenuVentas.add(ItemRegistrarventa);

        jMenuItem1.setText("Consultar venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuVentas.add(jMenuItem1);

        jMenuBar1.add(MenuVentas);

        MenuProductos.setText("Productos");

        ItemRegistrarproducto.setText("Administrar productos");
        ItemRegistrarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegistrarproductoActionPerformed(evt);
            }
        });
        MenuProductos.add(ItemRegistrarproducto);

        jMenuBar1.add(MenuProductos);

        Menuproveedores.setText("Proveedores");

        ItemRegistrarproveedor.setText("Aministrar proveedores");
        ItemRegistrarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegistrarproveedorActionPerformed(evt);
            }
        });
        Menuproveedores.add(ItemRegistrarproveedor);

        jMenuBar1.add(Menuproveedores);
        Menuproveedores.getAccessibleContext().setAccessibleDescription("");

        MenuCompra.setText("Compra");

        ItemRegistrarcompra.setText("Registrar compra");
        ItemRegistrarcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegistrarcompraActionPerformed(evt);
            }
        });
        MenuCompra.add(ItemRegistrarcompra);

        jMenuBar1.add(MenuCompra);

        Menureportes.setText("Reportes");

        ItemGenerarreporte.setText("Generar reporte");
        ItemGenerarreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemGenerarreporteActionPerformed(evt);
            }
        });
        Menureportes.add(ItemGenerarreporte);

        jMenuBar1.add(Menureportes);

        Menuusuarios.setText("Usuarios");

        ItemRegistrarusuario.setText("Administrar usuarios");
        ItemRegistrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegistrarusuarioActionPerformed(evt);
            }
        });
        Menuusuarios.add(ItemRegistrarusuario);

        jMenuBar1.add(Menuusuarios);

        jMenu5.setText("Cerrar sesión");

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemRegistrarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegistrarventaActionPerformed
        // TODO add your handling code here:
        frmRegistrarventa rv = new frmRegistrarventa();
        rv.setVisible(true);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(rv);
        rv.show();

    }//GEN-LAST:event_ItemRegistrarventaActionPerformed

    private void ItemRegistrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegistrarusuarioActionPerformed
        // TODO add your handling code here:
        Usuario us = new Usuario();
        ConsultasUsuario conus = new ConsultasUsuario();
        frmAdministrarusuarios intus = new frmAdministrarusuarios();

        CtrlRegistrarUsuario ctrpv = new CtrlRegistrarUsuario(us, conus, intus);
        CtrlConsultarUsuario ctrp = new CtrlConsultarUsuario(us, conus, intus);
        CtrlModificarUsuario tp = new CtrlModificarUsuario(us, conus, intus);
        CtrlEliminarUsuario tpl = new CtrlEliminarUsuario(us, conus, intus);
        CtrlModificarContraseña m = new CtrlModificarContraseña(us, conus, intus);
        intus.setVisible(true);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(intus);
        intus.show();

    }//GEN-LAST:event_ItemRegistrarusuarioActionPerformed

    private void ItemRegistrarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegistrarproveedorActionPerformed
        // TODO add your handling code here:
        Proveedor pv = new Proveedor();
        ConsultasProveedor conpv = new ConsultasProveedor();
        frmAdministrarproveedores intpv = new frmAdministrarproveedores();

        CtrlRegistrarproveedor ctrpv = new CtrlRegistrarproveedor(pv, conpv, intpv);
        CtrlConsultarproveedor conp = new CtrlConsultarproveedor(pv, conpv, intpv);
        CtrlModificarProveedor contp = new CtrlModificarProveedor(pv, conpv, intpv);
        CtrlEliminarProveedor conte = new CtrlEliminarProveedor(pv, conpv, intpv);
        conp.iniciar();
        intpv.setVisible(true);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(intpv);
        intpv.show();
    }//GEN-LAST:event_ItemRegistrarproveedorActionPerformed

    private void ItemRegistrarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegistrarproductoActionPerformed
        // TODO add your handling code here:
        Producto pd = new Producto();
        ConsultasProducto conpd = new ConsultasProducto();
        frmAAdministrarproductos intpv = new frmAAdministrarproductos();

        CtrlProducto ctrpd = new CtrlProducto(pd, conpd, intpv);
        CtrlConsultarProducto ctr = new CtrlConsultarProducto(pd, conpd, intpv);
        CtrlModificarProducto ctrr = new CtrlModificarProducto(pd, conpd, intpv);
        CtrlEliminarProducto cter = new CtrlEliminarProducto(pd, conpd, intpv);
        intpv.setVisible(true);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(intpv);
        intpv.show();

    }//GEN-LAST:event_ItemRegistrarproductoActionPerformed

    private void ItemRegistrarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegistrarcompraActionPerformed
        // TODO add your handling code here:
        frmRegistrarCompra rv = new frmRegistrarCompra();
        rv.setVisible(true);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(rv);
        rv.show();
    }//GEN-LAST:event_ItemRegistrarcompraActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frmIniciarSesion1 is = new frmIniciarSesion1();
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ItemGenerarreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemGenerarreporteActionPerformed
        // TODO add your handling code here:
        frmReportes bh= new frmReportes();
        bh.setVisible(true);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(bh);
        bh.show();
    }//GEN-LAST:event_ItemGenerarreporteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmConsultarVenta intr = new frmConsultarVenta();
        intr.setVisible(true);

        jDesktopPane1.removeAll();
        jDesktopPane1.add(intr);
        intr.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemGenerarreporte;
    private javax.swing.JMenuItem ItemRegistrarcompra;
    private javax.swing.JMenuItem ItemRegistrarproducto;
    private javax.swing.JMenuItem ItemRegistrarproveedor;
    private javax.swing.JMenuItem ItemRegistrarusuario;
    private javax.swing.JMenuItem ItemRegistrarventa;
    private javax.swing.JMenu MenuCompra;
    private javax.swing.JMenu MenuProductos;
    private javax.swing.JMenu MenuVentas;
    private javax.swing.JMenu Menuproveedores;
    private javax.swing.JMenu Menureportes;
    private javax.swing.JMenu Menuusuarios;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
